export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      empresas: { Row: { id: string; nome: string; logo: string | null; cnpj: string | null; telefone: string | null; email: string | null; endereco: string | null; cidade: string | null; estado: string | null; ativo: boolean; created_at: string; updated_at: string }; Insert: { id?: string; nome: string; logo?: string | null; cnpj?: string | null; telefone?: string | null; email?: string | null; endereco?: string | null; cidade?: string | null; estado?: string | null; ativo?: boolean; created_at?: string; updated_at?: string }; Update: { id?: string; nome?: string; logo?: string | null; cnpj?: string | null; telefone?: string | null; email?: string | null; endereco?: string | null; cidade?: string | null; estado?: string | null; ativo?: boolean; created_at?: string; updated_at?: string } }
      usuarios: { Row: { id: string; email: string; nome: string; empresa_id: string; cargo: string; avatar: string | null; ativo: boolean; created_at: string; updated_at: string }; Insert: { id?: string; email: string; nome: string; empresa_id: string; cargo: string; avatar?: string | null; ativo?: boolean; created_at?: string; updated_at?: string }; Update: { id?: string; email?: string; nome?: string; empresa_id?: string; cargo?: string; avatar?: string | null; ativo?: boolean; created_at?: string; updated_at?: string } }
      fornecedores: { Row: { id: string; empresa_id: string; nome: string; telefone: string | null; whatsapp: string | null; cidade: string | null; cpf_cnpj: string | null; observacoes: string | null; created_at: string; updated_at: string; created_by: string }; Insert: { id?: string; empresa_id: string; nome: string; telefone?: string | null; whatsapp?: string | null; cidade?: string | null; cpf_cnpj?: string | null; observacoes?: string | null; created_at?: string; updated_at?: string; created_by: string }; Update: { id?: string; empresa_id?: string; nome?: string; telefone?: string | null; whatsapp?: string | null; cidade?: string | null; cpf_cnpj?: string | null; observacoes?: string | null; created_at?: string; updated_at?: string; created_by?: string } }
      animais: { Row: { id: string; empresa_id: string; fornecedor_id: string; numero_lote: string; data_compra: string; peso_vivo: number; peso_carcaca: number; arrobas: number; preco_pago: number; frete: number; impostos: number; outras_despesas: number; valor_total: number; observacoes: string | null; fotos: string[] | null; notas_fiscais: string[] | null; created_at: string; updated_at: string; created_by: string }; Insert: { id?: string; empresa_id: string; fornecedor_id: string; numero_lote: string; data_compra: string; peso_vivo: number; peso_carcaca: number; arrobas: number; preco_pago: number; frete?: number; impostos?: number; outras_despesas?: number; valor_total: number; observacoes?: string | null; fotos?: string[] | null; notas_fiscais?: string[] | null; created_at?: string; updated_at?: string; created_by: string }; Update: { id?: string; empresa_id?: string; fornecedor_id?: string; numero_lote?: string; data_compra?: string; peso_vivo?: number; peso_carcaca?: number; arrobas?: number; preco_pago?: number; frete?: number; impostos?: number; outras_despesas?: number; valor_total?: number; observacoes?: string | null; fotos?: string[] | null; notas_fiscais?: string[] | null; created_at?: string; updated_at?: string; created_by?: string } }
      categorias: { Row: { id: string; empresa_id: string; nome: string; descricao: string | null; created_at: string }; Insert: { id?: string; empresa_id: string; nome: string; descricao?: string | null; created_at?: string }; Update: { id?: string; empresa_id?: string; nome?: string; descricao?: string | null; created_at?: string } }
      cortes: { Row: { id: string; empresa_id: string; animal_id: string; nome: string; peso: number; quantidade: number; categoria_id: string | null; preco_sugerido: number; preco_venda: number; observacoes: string | null; created_at: string; created_by: string }; Insert: { id?: string; empresa_id: string; animal_id: string; nome: string; peso: number; quantidade: number; categoria_id?: string | null; preco_sugerido: number; preco_venda: number; observacoes?: string | null; created_at?: string; created_by: string }; Update: { id?: string; empresa_id?: string; animal_id?: string; nome?: string; peso?: number; quantidade?: number; categoria_id?: string | null; preco_sugerido?: number; preco_venda?: number; observacoes?: string | null; created_at?: string; created_by?: string } }
      estoque: { Row: { id: string; empresa_id: string; animal_id: string; corte_id: string; nome: string; peso: number; quantidade: number; localizacao: string | null; data_entrada: string; validade: string | null; lote: string; codigo_interno: string | null; codigo_barras: string | null; created_at: string; updated_at: string }; Insert: { id?: string; empresa_id: string; animal_id: string; corte_id: string; nome: string; peso: number; quantidade: number; localizacao?: string | null; data_entrada: string; validade?: string | null; lote: string; codigo_interno?: string | null; codigo_barras?: string | null; created_at?: string; updated_at?: string }; Update: { id?: string; empresa_id?: string; animal_id?: string; corte_id?: string; nome?: string; peso?: number; quantidade?: number; localizacao?: string | null; data_entrada?: string; validade?: string | null; lote?: string; codigo_interno?: string | null; codigo_barras?: string | null; created_at?: string; updated_at?: string } }
      movimentacoes_estoque: { Row: { id: string; empresa_id: string; estoque_id: string; tipo: string; quantidade: number; peso: number; motivo: string | null; created_at: string; created_by: string }; Insert: { id?: string; empresa_id: string; estoque_id: string; tipo: string; quantidade: number; peso: number; motivo?: string | null; created_at?: string; created_by: string }; Update: { id?: string; empresa_id?: string; estoque_id?: string; tipo?: string; quantidade?: number; peso?: number; motivo?: string | null; created_at?: string; created_by?: string } }
      clientes: { Row: { id: string; empresa_id: string; nome: string; telefone: string | null; whatsapp: string | null; email: string | null; cpf_cnpj: string | null; endereco: string | null; observacoes: string | null; created_at: string; updated_at: string; created_by: string }; Insert: { id?: string; empresa_id: string; nome: string; telefone?: string | null; whatsapp?: string | null; email?: string | null; cpf_cnpj?: string | null; endereco?: string | null; observacoes?: string | null; created_at?: string; updated_at?: string; created_by: string }; Update: { id?: string; empresa_id?: string; nome?: string; telefone?: string | null; whatsapp?: string | null; email?: string | null; cpf_cnpj?: string | null; endereco?: string | null; observacoes?: string | null; created_at?: string; updated_at?: string; created_by?: string } }
      vendas: { Row: { id: string; empresa_id: string; cliente_id: string | null; tipo: string; forma_pagamento: string; valor_total: number; desconto: number | null; observacoes: string | null; created_at: string; created_by: string }; Insert: { id?: string; empresa_id: string; cliente_id?: string | null; tipo: string; forma_pagamento: string; valor_total: number; desconto?: number | null; observacoes?: string | null; created_at?: string; created_by: string }; Update: { id?: string; empresa_id?: string; cliente_id?: string | null; tipo?: string; forma_pagamento?: string; valor_total?: number; desconto?: number | null; observacoes?: string | null; created_at?: string; created_by?: string } }
      itens_venda: { Row: { id: string; venda_id: string; estoque_id: string; corte_nome: string; quantidade: number; peso: number; preco_unitario: number; subtotal: number }; Insert: { id?: string; venda_id: string; estoque_id: string; corte_nome: string; quantidade: number; peso: number; preco_unitario: number; subtotal: number }; Update: { id?: string; venda_id?: string; estoque_id?: string; corte_nome?: string; quantidade?: number; peso?: number; preco_unitario?: number; subtotal?: number } }
      despesas: { Row: { id: string; empresa_id: string; descricao: string; valor: number; data: string; categoria: string | null; observacoes: string | null; created_at: string; created_by: string }; Insert: { id?: string; empresa_id: string; descricao: string; valor: number; data: string; categoria?: string | null; observacoes?: string | null; created_at?: string; created_by: string }; Update: { id?: string; empresa_id?: string; descricao?: string; valor?: number; data?: string; categoria?: string | null; observacoes?: string | null; created_at?: string; created_by?: string } }
      receitas: { Row: { id: string; empresa_id: string; descricao: string; valor: number; data: string; categoria: string | null; observacoes: string | null; venda_id: string | null; created_at: string; created_by: string }; Insert: { id?: string; empresa_id: string; descricao: string; valor: number; data: string; categoria?: string | null; observacoes?: string | null; venda_id?: string | null; created_at?: string; created_by: string }; Update: { id?: string; empresa_id?: string; descricao?: string; valor?: number; data?: string; categoria?: string | null; observacoes?: string | null; venda_id?: string | null; created_at?: string; created_by?: string } }
      logs_auditoria: { Row: { id: string; empresa_id: string; usuario_id: string; acao: string; entidade: string; entidade_id: string; dados_anteriores: Json | null; dados_novos: Json | null; ip: string | null; created_at: string }; Insert: { id?: string; empresa_id: string; usuario_id: string; acao: string; entidade: string; entidade_id: string; dados_anteriores?: Json | null; dados_novos?: Json | null; ip?: string | null; created_at?: string }; Update: { id?: string; empresa_id?: string; usuario_id?: string; acao?: string; entidade?: string; entidade_id?: string; dados_anteriores?: Json | null; dados_novos?: Json | null; ip?: string | null; created_at?: string } }
      configuracoes: { Row: { id: string; empresa_id: string; chave: string; valor: string; created_at: string; updated_at: string }; Insert: { id?: string; empresa_id: string; chave: string; valor: string; created_at?: string; updated_at?: string }; Update: { id?: string; empresa_id?: string; chave?: string; valor?: string; created_at?: string; updated_at?: string } }
      notificacoes: { Row: { id: string; empresa_id: string; titulo: string; mensagem: string; tipo: string; lida: boolean; created_at: string }; Insert: { id?: string; empresa_id: string; titulo: string; mensagem: string; tipo: string; lida?: boolean; created_at?: string }; Update: { id?: string; empresa_id?: string; titulo?: string; mensagem?: string; tipo?: string; lida?: boolean; created_at?: string } }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
